//! Auto-generated Betti RDL executable for sir_demo
//! This file was generated by the Grey compiler backend.

use betti_rdl::Kernel;
use std::collections::HashMap;

pub struct sir_demoExecutable {
    kernel: Kernel,
    process_coords: HashMap<String, (i32, i32, i32)>,
}

impl sir_demoExecutable {
    pub fn new() -> Self {
        let mut executable = Self {
            kernel: Kernel::new(),
            process_coords: HashMap::new(),
        };
        
        // Initialize process coordinates
        executable.process_coords.insert("p0".to_string(), (0, 0, 0));
        executable.process_coords.insert("p1".to_string(), (1, 0, 0));
        executable.process_coords.insert("p10".to_string(), (2, 1, 0));
        executable.process_coords.insert("p11".to_string(), (3, 1, 0));
        executable.process_coords.insert("p12".to_string(), (4, 1, 0));
        executable.process_coords.insert("p13".to_string(), (5, 1, 0));
        executable.process_coords.insert("p14".to_string(), (6, 1, 0));
        executable.process_coords.insert("p15".to_string(), (7, 1, 0));
        executable.process_coords.insert("p16".to_string(), (0, 2, 0));
        executable.process_coords.insert("p17".to_string(), (1, 2, 0));
        executable.process_coords.insert("p18".to_string(), (2, 2, 0));
        executable.process_coords.insert("p19".to_string(), (3, 2, 0));
        executable.process_coords.insert("p2".to_string(), (2, 0, 0));
        executable.process_coords.insert("p20".to_string(), (4, 2, 0));
        executable.process_coords.insert("p21".to_string(), (5, 2, 0));
        executable.process_coords.insert("p22".to_string(), (6, 2, 0));
        executable.process_coords.insert("p23".to_string(), (7, 2, 0));
        executable.process_coords.insert("p24".to_string(), (0, 3, 0));
        executable.process_coords.insert("p25".to_string(), (1, 3, 0));
        executable.process_coords.insert("p26".to_string(), (2, 3, 0));
        executable.process_coords.insert("p27".to_string(), (3, 3, 0));
        executable.process_coords.insert("p28".to_string(), (4, 3, 0));
        executable.process_coords.insert("p29".to_string(), (5, 3, 0));
        executable.process_coords.insert("p3".to_string(), (3, 0, 0));
        executable.process_coords.insert("p30".to_string(), (6, 3, 0));
        executable.process_coords.insert("p31".to_string(), (7, 3, 0));
        executable.process_coords.insert("p32".to_string(), (0, 4, 0));
        executable.process_coords.insert("p33".to_string(), (1, 4, 0));
        executable.process_coords.insert("p34".to_string(), (2, 4, 0));
        executable.process_coords.insert("p35".to_string(), (3, 4, 0));
        executable.process_coords.insert("p36".to_string(), (4, 4, 0));
        executable.process_coords.insert("p37".to_string(), (5, 4, 0));
        executable.process_coords.insert("p38".to_string(), (6, 4, 0));
        executable.process_coords.insert("p39".to_string(), (7, 4, 0));
        executable.process_coords.insert("p4".to_string(), (4, 0, 0));
        executable.process_coords.insert("p40".to_string(), (0, 5, 0));
        executable.process_coords.insert("p41".to_string(), (1, 5, 0));
        executable.process_coords.insert("p42".to_string(), (2, 5, 0));
        executable.process_coords.insert("p43".to_string(), (3, 5, 0));
        executable.process_coords.insert("p44".to_string(), (4, 5, 0));
        executable.process_coords.insert("p45".to_string(), (5, 5, 0));
        executable.process_coords.insert("p46".to_string(), (6, 5, 0));
        executable.process_coords.insert("p47".to_string(), (7, 5, 0));
        executable.process_coords.insert("p48".to_string(), (0, 6, 0));
        executable.process_coords.insert("p49".to_string(), (1, 6, 0));
        executable.process_coords.insert("p5".to_string(), (5, 0, 0));
        executable.process_coords.insert("p50".to_string(), (2, 6, 0));
        executable.process_coords.insert("p51".to_string(), (3, 6, 0));
        executable.process_coords.insert("p52".to_string(), (4, 6, 0));
        executable.process_coords.insert("p53".to_string(), (5, 6, 0));
        executable.process_coords.insert("p54".to_string(), (6, 6, 0));
        executable.process_coords.insert("p55".to_string(), (7, 6, 0));
        executable.process_coords.insert("p56".to_string(), (0, 7, 0));
        executable.process_coords.insert("p57".to_string(), (1, 7, 0));
        executable.process_coords.insert("p58".to_string(), (2, 7, 0));
        executable.process_coords.insert("p59".to_string(), (3, 7, 0));
        executable.process_coords.insert("p6".to_string(), (6, 0, 0));
        executable.process_coords.insert("p60".to_string(), (4, 7, 0));
        executable.process_coords.insert("p61".to_string(), (5, 7, 0));
        executable.process_coords.insert("p62".to_string(), (6, 7, 0));
        executable.process_coords.insert("p63".to_string(), (7, 7, 0));
        executable.process_coords.insert("p7".to_string(), (7, 0, 0));
        executable.process_coords.insert("p8".to_string(), (0, 1, 0));
        executable.process_coords.insert("p9".to_string(), (1, 1, 0));
        executable
    }

    pub fn spawn_processes(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        self.kernel.spawn_process(0, 0, 0); // p0
        self.kernel.spawn_process(1, 0, 0); // p1
        self.kernel.spawn_process(2, 1, 0); // p10
        self.kernel.spawn_process(3, 1, 0); // p11
        self.kernel.spawn_process(4, 1, 0); // p12
        self.kernel.spawn_process(5, 1, 0); // p13
        self.kernel.spawn_process(6, 1, 0); // p14
        self.kernel.spawn_process(7, 1, 0); // p15
        self.kernel.spawn_process(0, 2, 0); // p16
        self.kernel.spawn_process(1, 2, 0); // p17
        self.kernel.spawn_process(2, 2, 0); // p18
        self.kernel.spawn_process(3, 2, 0); // p19
        self.kernel.spawn_process(2, 0, 0); // p2
        self.kernel.spawn_process(4, 2, 0); // p20
        self.kernel.spawn_process(5, 2, 0); // p21
        self.kernel.spawn_process(6, 2, 0); // p22
        self.kernel.spawn_process(7, 2, 0); // p23
        self.kernel.spawn_process(0, 3, 0); // p24
        self.kernel.spawn_process(1, 3, 0); // p25
        self.kernel.spawn_process(2, 3, 0); // p26
        self.kernel.spawn_process(3, 3, 0); // p27
        self.kernel.spawn_process(4, 3, 0); // p28
        self.kernel.spawn_process(5, 3, 0); // p29
        self.kernel.spawn_process(3, 0, 0); // p3
        self.kernel.spawn_process(6, 3, 0); // p30
        self.kernel.spawn_process(7, 3, 0); // p31
        self.kernel.spawn_process(0, 4, 0); // p32
        self.kernel.spawn_process(1, 4, 0); // p33
        self.kernel.spawn_process(2, 4, 0); // p34
        self.kernel.spawn_process(3, 4, 0); // p35
        self.kernel.spawn_process(4, 4, 0); // p36
        self.kernel.spawn_process(5, 4, 0); // p37
        self.kernel.spawn_process(6, 4, 0); // p38
        self.kernel.spawn_process(7, 4, 0); // p39
        self.kernel.spawn_process(4, 0, 0); // p4
        self.kernel.spawn_process(0, 5, 0); // p40
        self.kernel.spawn_process(1, 5, 0); // p41
        self.kernel.spawn_process(2, 5, 0); // p42
        self.kernel.spawn_process(3, 5, 0); // p43
        self.kernel.spawn_process(4, 5, 0); // p44
        self.kernel.spawn_process(5, 5, 0); // p45
        self.kernel.spawn_process(6, 5, 0); // p46
        self.kernel.spawn_process(7, 5, 0); // p47
        self.kernel.spawn_process(0, 6, 0); // p48
        self.kernel.spawn_process(1, 6, 0); // p49
        self.kernel.spawn_process(5, 0, 0); // p5
        self.kernel.spawn_process(2, 6, 0); // p50
        self.kernel.spawn_process(3, 6, 0); // p51
        self.kernel.spawn_process(4, 6, 0); // p52
        self.kernel.spawn_process(5, 6, 0); // p53
        self.kernel.spawn_process(6, 6, 0); // p54
        self.kernel.spawn_process(7, 6, 0); // p55
        self.kernel.spawn_process(0, 7, 0); // p56
        self.kernel.spawn_process(1, 7, 0); // p57
        self.kernel.spawn_process(2, 7, 0); // p58
        self.kernel.spawn_process(3, 7, 0); // p59
        self.kernel.spawn_process(6, 0, 0); // p6
        self.kernel.spawn_process(4, 7, 0); // p60
        self.kernel.spawn_process(5, 7, 0); // p61
        self.kernel.spawn_process(6, 7, 0); // p62
        self.kernel.spawn_process(7, 7, 0); // p63
        self.kernel.spawn_process(7, 0, 0); // p7
        self.kernel.spawn_process(0, 1, 0); // p8
        self.kernel.spawn_process(1, 1, 0); // p9
        Ok(())
    }

    pub fn inject_events(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        // Inject initial events to first process
        if let Some((x, y, z)) = self.process_coords.get("p0") {
            // Inject seed events to trigger process execution
            self.kernel.inject_event(*x, *y, *z, 1);
        }
        Ok(())
    }

    pub fn run(&mut self, max_events: i32) -> Result<HashMap<String, u64>, Box<dyn std::error::Error>> {
        let events_in_run = self.kernel.run(max_events);

        let mut results = HashMap::new();
        results.insert("events_in_run".to_string(), events_in_run as u64);
        results.insert("events_processed".to_string(), self.kernel.events_processed());
        results.insert("current_time".to_string(), self.kernel.current_time());
        results.insert("process_count".to_string(), self.kernel.process_count() as u64);
        Ok(results)
    }

}


#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_sir_demo_execution() {
        let mut executable = sir_demoExecutable::new();
        executable.spawn_processes().unwrap();
        executable.inject_events().unwrap();
        
        let results = executable.run(100).unwrap();
        
        assert!(results.contains_key("events_processed"));
        assert_eq!(results["process_count"], 64 as u64);
    }
}
